# Generated by Django 4.2 on 2023-05-01 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Token',
        ),
    ]
