# Generated by Django 4.2 on 2023-05-02 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('SHIPPING', 'Shipping'), ('DELIVERED', 'Delivered')], default='PENDING', max_length=10),
        ),
    ]
