# Generated by Django 4.2 on 2023-05-04 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_rename_payed_order_paid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='paid',
        ),
    ]
